<!DOCTYPE html>
<html lang="zh_CN" data-theme-mode="light" data-light-theme="daylight" data-dark-theme="midnight">
<head>
  
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <link rel="stylesheet" type="text/css" id="baseStyle" href="https://fastly.jsdelivr.net/gh/siyuan-note/oceanpress@latest/apps/frontend/public/notebook/stage/build/export/base.css?2.10.5"/>
  <script>
  function isNightTime() {
    const currentHour = new Date().getHours();
    return currentHour >= 18 || currentHour < 6;
  }
  document.write('<link rel="stylesheet" type="text/css" id="themeDefaultStyle" href="https://fastly.jsdelivr.net/gh/siyuan-note/oceanpress@latest/apps/frontend/public/notebook/appearance/themes/'+(isNightTime()?'midnight':'daylight')+'/theme.css?2.10.5"/>');
  </script>
  <link rel="stylesheet" type="text/css" href="https://fastly.jsdelivr.net/gh/siyuan-note/oceanpress@latest/apps/frontend/public/notebook/appearance/oceanpress.css"/>
  <title>小心的使用promise.finally</title>
</head>
<body>
  
  <div class="protyle-wysiwyg protyle-wysiwyg--attr" id="preview">
  <div style="min-height: 150px;" id="20210811164611-ktksld1" data-node-id="20210811164611-ktksld1" data-type="NodeDocument" updated="20210811165847" data-subtype="h1" class="h1" scroll="&#123;&quot;rootId&quot;:&quot;20210811164611-ktksld1&quot;,&quot;startId&quot;:&quot;20210811164611-jwt8gq8&quot;,&quot;endId&quot;:&quot;20210811164806-f0kcg6f&quot;,&quot;scrollTop&quot;:0,&quot;focusId&quot;:&quot;20210811164703-zltlvhd&quot;,&quot;focusStart&quot;:17,&quot;focusEnd&quot;:17&#125;"></div><div id="20210811164611-ktksld1" data-node-id="20210811164611-ktksld1" data-type="NodeDocument" updated="20210811165847" data-subtype="h1" class="h1" scroll="&#123;&quot;rootId&quot;:&quot;20210811164611-ktksld1&quot;,&quot;startId&quot;:&quot;20210811164611-jwt8gq8&quot;,&quot;endId&quot;:&quot;20210811164806-f0kcg6f&quot;,&quot;scrollTop&quot;:0,&quot;focusId&quot;:&quot;20210811164703-zltlvhd&quot;,&quot;focusStart&quot;:17,&quot;focusEnd&quot;:17&#125;" data-type="NodeHeading" class="h1">小心的使用promise.finally</div><div id="20210811164611-jwt8gq8" data-node-id="20210811164611-jwt8gq8" data-type="NodeParagraph" updated="20210811164702" class="p">有网友问了一个问题 ： 
<a href="https://deno.js.cn/t/topic/873">问一个关于async 嵌套 catch的问题，这到底有没有catch到呢？</a>
</div>
<div id="20210811164703-zltlvhd" data-node-id="20210811164703-zltlvhd" data-type="NodeParagraph" updated="20210811164730" class="p">这个问题中的代码经过极致简化后如下
</div>
 <div id="20210811164730-de1gxhi" data-node-id="20210811164730-de1gxhi" data-type="NodeIFrame" updated="20210811164749" class="iframe" custom-config="&#123;&quot;source&quot;:&quot;&quot;,&quot;inside&quot;:&quot;inside&quot;,&quot;title&quot;:&quot;&quot;,&quot;preamble&quot;:&quot;&quot;,&quot;version&quot;:&quot;16.6.0&quot;&#125;" custom-z-getblockattr-3214143905064149="&#123;&quot;block_id&quot;:&quot;20210811164730-de1gxhi&quot;,&quot;box&quot;:&quot;20210816161940-zo21go1&quot;,&quot;id&quot;:&quot;20230913113723-9icidzt&quot;,&quot;name&quot;:&quot;custom-config&quot;,&quot;path&quot;:&quot;/20210816161944-cn1ky4x/20210811164611-ktksld1.sy&quot;,&quot;root_id&quot;:&quot;20210811164611-ktksld1&quot;,&quot;type&quot;:&quot;b&quot;,&quot;value&quot;:&quot;&#123;\&quot;source\&quot;:\&quot;async function deadline(p) &#123;\\n    // 去掉 await 则会报错 finally，只是说无论结果是否成功，都会执行 finally。但不会 catch error\\n    // 原来的代码问题在于 p 被执行的时候既没有被 await 同步，也没有被 .catch 异步，所以没有被 catch error\\n    await p.finally(() =&gt; &#123;\\n        console.log(`1`);\\n    &#125;);\\n&#125;\\nasync function main() &#123;\\n    try &#123;\\n        await deadline(Promise.reject(\\\&quot;boom\\\&quot;));\\n    &#125; catch (error) &#123;\\n        console.log(`catch error $&#123;error&#125;`);\\n    &#125;\\n&#125;\\n\\nprocess.on('uncaughtException', err =&gt; &#123;\\n    console.error('有一个未捕获的错误', err);\\n    process.exit(1); //强制性的（根据 Node.js 文档）\\n&#125;);\\n\\nmain();\&quot;,\&quot;inside\&quot;:\&quot;inside\&quot;,\&quot;title\&quot;:\&quot;\&quot;,\&quot;preamble\&quot;:\&quot;\&quot;,\&quot;version\&quot;:\&quot;16.x.x\&quot;&#125;&quot;&#125;" custom-z-ir-3779652868977396="{&quot;block_id&quot;:&quot;20210811164730-de1gxhi&quot;,&quot;box&quot;:&quot;note&quot;,&quot;id&quot;:&quot;&quot;,&quot;name&quot;:&quot;custom-config&quot;,&quot;path&quot;:&quot;/other/小心的使用promise.finally.sy&quot;,&quot;root_id&quot;:&quot;20210811164611-ktksld1&quot;,&quot;type&quot;:&quot;b&quot;,&quot;value&quot;:&quot;{&amp;quot;source&amp;quot;:&amp;quot;async function deadline(p) {\\n    // 去掉 await 则会报错 finally，只是说无论结果是否成功，都会执行 finally。但不会 catch error\\n    // 原来的代码问题在于 p 被执行的时候既没有被 await 同步，也没有被 .catch 异步，所以没有被 catch error\\n    await p.finally(() =&amp;gt; {\\n        console.log(`1`);\\n    });\\n}\\nasync function main() {\\n    try {\\n        await deadline(Promise.reject(\\&amp;quot;boom\\&amp;quot;));\\n    } catch (error) {\\n        console.log(`catch error ${error}`);\\n    }\\n}\\n\\nprocess.on('uncaughtException', err =&amp;gt; {\\n    console.error('有一个未捕获的错误', err);\\n    process.exit(1); //强制性的（根据 Node.js 文档）\\n});\\n\\nmain();&amp;quot;,&amp;quot;inside&amp;quot;:&amp;quot;inside&amp;quot;,&amp;quot;title&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;preamble&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;version&amp;quot;:&amp;quot;16.x.x&amp;quot;}&quot;}" custom-z-ss-186603330745775="{&quot;block_id&quot;:&quot;20210811164730-de1gxhi&quot;,&quot;box&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;name&quot;:&quot;custom-config&quot;,&quot;path&quot;:&quot;/20210816161940-zo21go1/20210816161944-cn1ky4x/20210811164611-ktksld1.sy&quot;,&quot;root_id&quot;:&quot;20210811164611-ktksld1&quot;,&quot;type&quot;:&quot;b&quot;,&quot;value&quot;:&quot;{&amp;quot;source&amp;quot;:&amp;quot;async function deadline(p) {\\n    // 去掉 await 则会报错 finally，只是说无论结果是否成功，都会执行 finally。但不会 catch error\\n    // 原来的代码问题在于 p 被执行的时候既没有被 await 同步，也没有被 .catch 异步，所以没有被 catch error\\n    await p.finally(() =&amp;gt; {\\n        console.log(`1`);\\n    });\\n}\\nasync function main() {\\n    try {\\n        await deadline(Promise.reject(\\&amp;quot;boom\\&amp;quot;));\\n    } catch (error) {\\n        console.log(`catch error ${error}`);\\n    }\\n}\\n\\nprocess.on('uncaughtException', err =&amp;gt; {\\n    console.error('有一个未捕获的错误', err);\\n    process.exit(1); //强制性的（根据 Node.js 文档）\\n});\\n\\nmain();&amp;quot;,&amp;quot;inside&amp;quot;:&amp;quot;inside&amp;quot;,&amp;quot;title&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;preamble&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;version&amp;quot;:&amp;quot;16.x.x&amp;quot;}&quot;}">
    <div class="iframe-content">
    <iframe src="/widgets/run-code/index.html" data-src="" border="0" frameborder="no" framespacing="0" allowfullscreen="true" style="width: 1006px; height: 644px;"></iframe>
    </div>
  </div>
<div id="20210811164806-f0kcg6f" data-node-id="20210811164806-f0kcg6f" data-type="NodeParagraph" updated="20210811165847" class="p">里面的注释大致说明了问题所在，我以前使用 finally 的时候很少考虑此问题，但事实上如果不小心处理的话很容易出现未捕获的异常
</div>

  </div>
  <script src="https://fastly.jsdelivr.net/gh/siyuan-note/oceanpress@latest/apps/frontend/public/notebook/appearance/icons/material/icon.js?2.10.5"></script>
  <script src="https://fastly.jsdelivr.net/gh/siyuan-note/oceanpress@latest/apps/frontend/public/notebook/stage/build/export/protyle-method.js?2.10.5"></script>
  <script src="https://fastly.jsdelivr.net/gh/siyuan-note/oceanpress@latest/apps/frontend/public/notebook/stage/protyle/js/lute/lute.min.js?2.10.5"></script>
  <script>
    window.siyuan = {
      config: {
        appearance: {
          mode: isNightTime()?1:0,//主题 明亮=0 暗黑=1
          codeBlockThemeDark: "base16/dracula",
          codeBlockThemeLight: "github",
        },
        editor: {
          codeLineWrap: true,
          codeLigatures: false,
          plantUMLServePath: "https://www.plantuml.com/plantuml/svg/~1",
          codeSyntaxHighlightLineNum: true,
          katexMacros: JSON.stringify({}),
        },
      },
      languages: { copy: "复制" },
    };
    const cdn = "https://fastly.jsdelivr.net/gh/siyuan-note/oceanpress@latest/apps/frontend/public/notebook/stage/protyle";
    const previewElement = document.getElementById("preview");

    Protyle.highlightRender(previewElement, cdn);
    Protyle.mathRender(previewElement, cdn, false);
    Protyle.mermaidRender(previewElement, cdn);
    Protyle.flowchartRender(previewElement, cdn);
    Protyle.graphvizRender(previewElement, cdn);
    Protyle.chartRender(previewElement, cdn);
    Protyle.mindmapRender(previewElement, cdn);
    Protyle.abcRender(previewElement, cdn);
    Protyle.htmlRender(previewElement);
    Protyle.plantumlRender(previewElement, cdn);
    document.querySelectorAll(".protyle-action__copy").forEach((item) => {
      item.addEventListener("click", (event) => {
        navigator.clipboard.writeText(
          item.parentElement.nextElementSibling.textContent.trimEnd(),
        );
        event.preventDefault();
        event.stopPropagation();
      });
    });
  </script>
  <footer>
<p style="text-align:center;margin:15px 0;">
  技术支持：
  <a target="_blank" href="https://github.com/2234839/oceanPress_js">OceanPress</a>|
    <a target="_blank" href="https://heartstack.space/user/%E5%AD%90%E8%99%9A/posts">崮生（子虚）</a> |
    <a target="_blank" href="//beian.miit.gov.cn">湘ICP备18021783号-1</a>
</p>
</footer>
</body>
</html>